### PR TITLE
Add note about password length

### LINKED ISSUE #29: Incorrect Password Error
```
$ ./knock ~/Desktop/xxxxxxxxxxxxxxxx.acsm 
This device is not registered with Adobe.
Enter your Adobe account's email address: xxxxxx@xxxxxx.xxxx
Enter your Adobe account's password: 
Registering this device with Adobe...
ERROR: Incorrect password
```
The password is correct. I'm pretty sure since I'm connected to the Adobe website.
Do you have any idea?

### PR DESCRIPTION
**Pull request by akirataguchi115**
Closes #29
Solution courtesy of [whowantsmybigdata](https://github.com/whowantsmybigdata).

### CODE REVIEW

**Comment by BentonEdmondson** [comment]
Have we verified that 11-word passwords do not work?

**Comment by akirataguchi115** [comment]
> Have we verified that 11-word passwords do not work?

Not really. I guess we could try increasing the password length overtime or just find out which line of bug causes this limitation.

**Comment by BentonEdmondson** [comment]
Yeah we'd want to find the exact limit. Guess and check will be the best strat because I'm fairly certain this is an error in either libgourou (dependency) or their servers. Also along with the readme change I would add a check in the software itself that gives a nice error message before even trying to use a password that's too long.

**Comment by fz6** [comment]
FWIW I have a 14 character password (fairly equal mix of letters, numbers + symbols) and it works fine.

**Comment by akirataguchi115** [comment]
I don't really see any reason why this still shouldn't be documented at least in the README for the time being.

**Comment by BentonEdmondson** [comment]
I'll merge this. Logins will be removed very soon (anonymous auth instead), but in the meantime yeah this seems like it can only help. Thanks @akirataguchi115

**Pull request merged**
